[package]
name = "webchat"
description = "WASM code in my web chat (I don't have a name for it yet)"
version = "4.1.3"
edition = "2021"
authors = ["S.C. Lorentz <113468900+SCLorentz@users.noreply.github.com>"]

[dependencies]
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]

#[dependencies.uuid]
#version = "1.10.0"
#eatures = ["v4", "fast-rng", "macro-diagnostics"]

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = "z"
strip = true  # Automatically strip symbols from the binary.
lto = true
